data:
    dataset: clevr
    data_root_dir : /private/home/tinayujiang/data/n2nmn_CLEVR
    preprocess_model : vgg_pool5
    vocab_question_file : vocabulary_clevr.txt
    vocab_layout_file : vocabulary_layout.txt
    vocab_answer_file : answers_clevr.txt
    imdb_file_trn : imdb_trn.npy
    image_depth_first: True

output:
    root_dir: ~/temp/temp_out
    exp_name: clevr_gt_rl 
model:
    model_type: gt+rl
    model_path: 
    image_height : 10
    image_width : 15
    in_image_dim : 512
    embed_dim_txt : 300
    embed_dim_nmn : 300
    hidden_size : 512
    num_layers : 2
    encoder_dropout : 0
    decoder_dropout : 0
    decoder_sampling : True
    T_encoder : 45
    T_decoder : 10
    N : 64
    lambda_entropy : 0.005
    prune_filter_module : True
    use_qpn : True
    qpn_dropout : True
    reduce_visfeat_dim : False

training_parameters:
    weight_decay : 5.0e-6
    baseline_decay : 0.99
    max_iter : 80000
    snapshot_interval : 10000
    max_grad_l2_norm: 10
    learning_rate : 0.0001

    
    
    
    
