data:
    dataset: vqa
    data_root_dir : /private/home/tinayujiang/data/n2nmn_vqa
    preprocess_model : resnet_res5c
    vocab_question_file : vocabulary_vqa.txt
    vocab_layout_file : vocabulary_layout.txt
    vocab_answer_file : answers_vqa.txt
    imdb_file_trn : imdb_trn.npy
    image_depth_first: False
output:
    root_dir: ~/temp/temp_out
    exp_name: vqa_scratch 
model:
    model_type: scratch
    image_height : 14
    image_width : 14
    in_image_dim : 2048
    embed_dim_txt : 300
    embed_dim_nmn : 300
    hidden_size : 1000
    num_layers : 2
    encoder_dropout : 0.1
    decoder_dropout : 0.1
    decoder_sampling : True
    T_encoder : 26
    T_decoder : 13
    N : 64
    lambda_entropy : 0.01
    prune_filter_module : True
    use_qpn : True
    qpn_dropout : True
    reduce_visfeat_dim : False

training_parameters:
    weight_decay : 0
    baseline_decay : 0.99
    max_iter : 120000
    snapshot_interval : 10000
    max_grad_l2_norm: 10
    learning_rate : 0.001

    
    
    
    
